import { Minus, Plus, ShoppingBag, X } from 'lucide-react'
import { businessConfig } from '../config/business'
import type { CartItem } from '../types'
import { formatCurrency } from '../utils/currency'

type Props = { open: boolean; items: CartItem[]; subtotal: number; onClose: () => void; onChange: (key: string, delta: number) => void; onRemove: (key: string) => void; onClear: () => void; onCheckout: () => void }

export function CartDrawer({ open, items, subtotal, onClose, onChange, onRemove, onClear, onCheckout }: Props) {
  return <><div className={open ? 'overlay show' : 'overlay'} onClick={onClose} /><aside className={open ? 'drawer open' : 'drawer'} aria-label="Carrito de compra" aria-hidden={!open}><div className="drawer-head"><div><p className="eyebrow">TU MESA</p><h2>El pedido</h2></div><button onClick={onClose} aria-label="Cerrar carrito"><X /></button></div>{items.length === 0 ? <div className="empty-cart"><ShoppingBag size={50} strokeWidth={1.3} aria-hidden="true" /><h3>Tu pedido está vacío</h3><p>Elegí algo de la carta y aparece acá.</p><button className="primary" onClick={onClose}>Ir a la carta</button></div> : <><div className="cart-list">{items.map(item => { const unit = item.product.price + item.selectedExtras.reduce((s, x) => s + x.price, 0); return <article className="cart-item" key={item.key}><img src={item.product.image} alt="" /><div className="cart-item-copy"><h3>{item.product.name}</h3>{item.selectedExtras.map(x => <small key={x.id}>+ {x.name}</small>)}{item.note && <small>Nota: {item.note}</small>}<b>{formatCurrency(unit * item.quantity)}</b></div><div className="cart-item-actions"><button className="remove" onClick={() => onRemove(item.key)} aria-label={`Eliminar ${item.product.name}`}><X size={17} /></button><div className="quantity"><button onClick={() => onChange(item.key, -1)} aria-label="Disminuir cantidad"><Minus size={14} /></button><span>{item.quantity}</span><button onClick={() => onChange(item.key, 1)} aria-label="Aumentar cantidad"><Plus size={14} /></button></div></div></article> })}</div><div className="cart-summary"><p><span>Subtotal</span><b>{formatCurrency(subtotal)}</b></p><p className="shipping-note">El envío se suma al elegir entrega.</p><p className="total"><span>Total estimado</span><b>{formatCurrency(subtotal + businessConfig.deliveryCost)}</b></p><button className="primary wide" onClick={onCheckout}>Continuar con mis datos</button><button className="clear" onClick={onClear}>Vaciar pedido</button></div></>}</aside></>
}
